### ISSUE TITLE
QA-Project Setting-Global variable functionality is not working.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#287]
When user adds the value in Global variable setting and go to a page section, need to define the global variable then preview page it's not showing those changes.

**Comment by fsaiyedOB** [comment]
Resolved

**Comment by acharotariya** [comment]
not working...!!!

**Comment by Nikunj025** [comment]
In Global Variable Only Text and HTML components are working.
Image and Hyperlink Components are still not working.

**Comment by fsaiyedOB** [comment]
For Image and Hyperlink components, you need to select the outer div and set the settings. This issue is checked and is working fine.

**Comment by qajha** [comment]
Issue now in QA server
